---

- hosts: all

  vars:
    upgradecmd: wget -O /home/admin/Downloads/mcraft_play.yml https://raw.githubusercontent.com/jorg-j/ansibleminecraft/main/mcraft_play.yml; ansible-playbook /home/admin/Downloads/mcraft_play.yml
    install_deb: true

  tasks:

  - name: adding alias for easier upgrades
    ansible.builtin.lineinfile:
      path: /home/admin/.bashrc
      regexp: '^alias mcraft'
      line: 'alias mcraft="{{ upgradecmd }}"'

  - name: Downloading minecraft deb file
    get_url:
      url: https://launcher.mojang.com/download/Minecraft.deb
      dest: /home/pi/Downloads/Minecraft.deb
  
  - name: Install Minecraft .deb package
    apt:
      deb: /home/pi/Downloads/Minecraft.deb
    when: install_deb | bool

