


---

- hosts: localhost

  vars:
    upgradecmd: wget -O /home/m/Downloads/mcraft_play.yml https://raw.githubusercontent.com/jorg-j/ansibleminecraft/main/mcraft_play.yml; ansible-playbook /home/m/Downloads/mcraft_play.yml
    install_mcraft: true
    install_discord: true
  tasks:
  

  - name: Ensure Alias in bashrc mcupgrade
    lineinfile:
      path: /home/m/.bashrc
      line: 'alias mcupgrade="{{ upgradecmd }}"'
      state: present

  - name: Ensure Alias in bashrc update
    lineinfile:
      path: /home/m/.bashrc
      line: 'alias ud="sudo apt update && sudo apt upgrade -y"'
      state: present

  - name: Downloading minecraft deb file
    get_url:
      url: https://launcher.mojang.com/download/Minecraft.deb
      dest: /home/m/Downloads/Minecraft.deb
    when: install_mcraft | bool
  
  - name: Install Minecraft .deb package
    become: true
    apt:
      deb: /home/m/Downloads/Minecraft.deb
    when: install_mcraft | bool

  - name: Downloading Discord deb file
    get_url:
      url: https://discordapp.com/api/download?platform=linux&format=deb
      dest: /home/m/Downloads/discord.deb
    when: install_discord | bool

  - name: Install Discord .deb package
    become: true
    apt:
      deb: /home/m/Downloads/discord.deb
    when: install_discord | bool


